import { jsPDF } from 'jspdf';
import autoTable, { applyPlugin } from 'jspdf-autotable';
import * as XLSX from 'xlsx';

// Grade → description
const GRADE_LABELS = { A: 'Excellent', B: 'Very Good', C: 'Good', D: 'Pass', F: 'Fail' };

const SUBJECTS = [
  'Mathematics','English','Kiswahili','Chemistry','Physics',
  'Biology','History','Geography','CRE','Computer Studies','Business Studies'
];

function autoGrade(avg) {
  if (avg >= 80) return 'A';
  if (avg >= 70) return 'B';
  if (avg >= 60) return 'C';
  if (avg >= 50) return 'D';
  return 'F';
}

export function getRemarks(avg) {
  if (avg >= 80) {
    return {
      teacher: "An outstanding performance. Keep up the excellent work!",
      principal: "Excellent results. You have shown great dedication to your studies."
    };
  } else if (avg >= 70) {
    return {
      teacher: "A very good performance. Keep aiming higher.",
      principal: "Very good effort. Continue working hard to achieve even better results."
    };
  } else if (avg >= 60) {
    return {
      teacher: "A good performance, but there is still room for improvement.",
      principal: "Good results. With a bit more effort, you can perform much better."
    };
  } else if (avg >= 50) {
    return {
      teacher: "A fair performance. You need to put in more effort in your weak areas.",
      principal: "Average results. Please dedicate more time to your studies."
    };
  } else {
    return {
      teacher: "A weak performance. You must work much harder next term.",
      principal: "Below average results. Ensure you consult your teachers and improve."
    };
  }
}

// Register the autoTable plugin
applyPlugin(jsPDF);

/**
 * Generates an Excel report from dashboard data
 */
export const generateExcelReport = (data) => {
  const { stats, attendance, performance, classes } = data;

  const workbook = XLSX.utils.book_new();

  // 1. Overview Sheet
  const overviewData = [
    ["UDIRA School Management System - Summary Report"],
    ["Generated on", new Date().toLocaleString()],
    [],
    ["Metric", "Value", "Trend"],
    ["Total Students", stats.totalStudents, "+12%"],
    ["Total Teachers", stats.totalTeachers, "+5%"],
    ["Total Classes", stats.totalClasses, "+2%"],
    ["Attendance Today", stats.attendanceToday + "%", "+3%"],
  ];
  const overviewWS = XLSX.utils.aoa_to_sheet(overviewData);
  XLSX.utils.book_append_sheet(workbook, overviewWS, "Overview");

  // 2. Attendance Sheet
  const attendanceWS = XLSX.utils.json_to_sheet(attendance);
  XLSX.utils.book_append_sheet(workbook, attendanceWS, "Attendance Trend");

  // 3. Class Distribution Sheet
  const classesWS = XLSX.utils.json_to_sheet(classes);
  XLSX.utils.book_append_sheet(workbook, classesWS, "Classes");

  // 4. Performance Sheet
  const performanceWS = XLSX.utils.json_to_sheet(performance);
  XLSX.utils.book_append_sheet(workbook, performanceWS, "Student Performance");

  // Write and Save
  XLSX.writeFile(workbook, `UDIRA_Report_${Date.now()}.xlsx`);
};

/**
 * Generates a PDF report from dashboard data
 */
export const generatePDFReport = (data) => {
  const { stats, attendance, user } = data;
  const doc = new jsPDF();
  const timestamp = new Date().toLocaleString();

  // Branding & Header
  doc.setFillColor(47, 102, 96); // UDIRA Green
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("UDIRA MANAGEMENT SYSTEM", 15, 25);
  
  doc.setFontSize(10);
  doc.text(`Official System Report | Generated by ${user?.name || 'Admin'}`, 15, 33);

  // Body Title
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(18);
  doc.text("School Overview Summary", 15, 55);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Date: ${timestamp}`, 15, 62);

  // Stats Table
  const statsRows = [
    ["Metric", "Current Value", "Weekly Change"],
    ["Total Students", stats.totalStudents.toString(), "+12%"],
    ["Total Teachers", stats.totalTeachers.toString(), "+5%"],
    ["Total Classes", stats.totalClasses.toString(), "+2%"],
    ["Daily Attendance", `${stats.attendanceToday}%`, "+3%"],
  ];

  autoTable(doc, {
    startY: 70,
    head: [statsRows[0]],
    body: statsRows.slice(1),
    theme: 'grid',
    headStyles: { fillColor: [47, 102, 96] },
    margin: { left: 15 },
  });

  // Attendance Section
  doc.setFontSize(16);
  doc.setTextColor(40, 40, 40);
  doc.text("Weekly Attendance Trend", 15, doc.lastAutoTable.finalY + 15);

  const attendanceRows = attendance.map(item => [item.date, item.present, item.absent]);
  
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    head: [["Day", "Present Students", "Absent Students"]],
    body: attendanceRows,
    theme: 'striped',
    headStyles: { fillColor: [47, 102, 96] },
    margin: { left: 15 },
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount} | UDIRA School Management System`, 105, 285, null, null, "center");
  }

  doc.save(`UDIRA_Report_${Date.now()}.pdf`);
};

/**
 * Generates a PDF result report card for a single student.
 * @param {object} student - ranked student object with .subjects, .student_name, etc.
 * @param {string} term - e.g. "Term 1"
 * @param {string} year - e.g. "2026"
 */
export const generateResultsPDF = (student, term = '', year = '') => {
  const doc = new jsPDF();
  drawStudentReportCard(doc, student, term, year);
  
  // Footer
  addReportCardFooters(doc);

  doc.save(`Result_${student.student_name.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
};

/**
 * Helper to draw a single student's report card on the current page
 */
const drawStudentReportCard = (doc, student, term, year) => {
  // ── Header banner ──────────────────────────────────────────────
  doc.setFillColor(47, 102, 96);
  doc.rect(0, 0, 210, 38, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('UDIRA HIGH SCHOOL', 15, 18);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Official Academic Result Report', 15, 27);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 15, 33);

  // ── Student info block ──────────────────────────────────────────
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(student.student_name, 15, 52);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  const meta = [
    `Admission No: ${student.admission_number}`,
    `Class: ${student.class_name}`,
    term ? `Term: ${term}` : '',
    year ? `Year: ${year}` : '',
    `Position: #${student.position}`,
  ].filter(Boolean).join('   |   ');
  doc.text(meta, 15, 59);

  // ── Summary strip ───────────────────────────────────────────────
  const summaryData = [
    ['Total Marks', `${student.total_marks} / ${student.total_possible}`],
    ['Average %', `${student.average_percentage}%`],
    ['Overall Grade', `${student.overall_grade} — ${GRADE_LABELS[student.overall_grade] || ''}`],
    ['Subjects Sat', student.subjects_count.toString()],
    ['Position', `#${student.position}`],
  ];

  autoTable(doc, {
    startY: 65,
    head: [['Item', 'Result']],
    body: summaryData,
    theme: 'grid',
    headStyles: { fillColor: [47, 102, 96] },
    columnStyles: { 0: { fontStyle: 'bold' } },
    margin: { left: 15, right: 15 },
  });

  // ── Subject breakdown ───────────────────────────────────────────
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(40, 40, 40);
  doc.text('Subject-by-Subject Breakdown', 15, doc.lastAutoTable.finalY + 12);

  const subjectRows = SUBJECTS.map((sub, i) => {
    const mark = student.subjects[sub];
    const grade = mark != null ? autoGrade(mark) : '—';
    const status = mark == null ? 'Pending' : mark >= 50 ? 'PASS' : 'FAIL';
    return [
      (i + 1).toString(),
      sub,
      mark != null ? mark.toString() : 'N/A',
      '100',
      grade,
      status,
    ];
  });

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 16,
    head: [['#', 'Subject', 'Marks', 'Out of', 'Grade', 'Result']],
    body: subjectRows,
    theme: 'striped',
    headStyles: { fillColor: [47, 102, 96] },
    columnStyles: {
      0: { halign: 'center', cellWidth: 10 },
      2: { halign: 'center', fontStyle: 'bold' },
      3: { halign: 'center' },
      4: { halign: 'center', fontStyle: 'bold' },
      5: { halign: 'center' },
    },
    didDrawCell: (data) => {
      if (data.column.index === 5 && data.section === 'body') {
        const val = data.cell.raw;
        if (val === 'PASS') data.cell.styles.textColor = [34, 197, 94];
        if (val === 'FAIL') data.cell.styles.textColor = [239, 68, 68];
      }
    },
    margin: { left: 15, right: 15 },
  });

  // ── Remarks ─────────────────────────────────────────────────────
  const remarks = getRemarks(student.average_percentage);
  
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);
  
  const currentY = doc.lastAutoTable.finalY + 15;
  
  doc.setFont('helvetica', 'bold');
  doc.text("Class Teacher's Remarks:", 15, currentY);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(80, 80, 80);
  doc.text(remarks.teacher, 15, currentY + 6);
  
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(40, 40, 40);
  doc.text("Principal's Remarks:", 15, currentY + 18);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(80, 80, 80);
  doc.text(remarks.principal, 15, currentY + 24);

  // Signatures
  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  
  doc.line(15, currentY + 45, 75, currentY + 45);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text("Class Teacher's Signature", 15, currentY + 50);
  
  doc.line(120, currentY + 45, 180, currentY + 45);
  doc.text("Principal's Signature", 120, currentY + 50);
};

const addReportCardFooters = (doc) => {
  // ── Footer ───────────────────────────────────────────────────────
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text(
      `Page ${i} of ${pages}  |  UDIRA HIGH SCHOOL — Result Report  |  Confidential`,
      105, 290, null, null, 'center'
    );
  }
};

/**
 * Generates a single PDF containing report cards for ALL students in the rankings array.
 * Each student's report card starts on a new page.
 */
export const generateAllResultsPDF = (rankings, term = '', year = '') => {
  if (!rankings || rankings.length === 0) return;
  
  const doc = new jsPDF();
  
  rankings.forEach((student, index) => {
    if (index > 0) {
      doc.addPage();
    }
    drawStudentReportCard(doc, student, term, year);
  });
  
  addReportCardFooters(doc);
  
  doc.save(`All_Report_Cards_${term || 'All'}_${year || 'All'}_${Date.now()}.pdf`);
};

/**
 * Generates a PDF for the full class examination rankings.
 * @param {Array} rankings - array of ranked student objects
 * @param {string} term
 * @param {string} year
 */
export const generateRankingsPDF = (rankings, term = '', year = '') => {
  const doc = new jsPDF({ orientation: 'landscape' });

  // Header
  doc.setFillColor(47, 102, 96);
  doc.rect(0, 0, 297, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('UDIRA HIGH SCHOOL — Examination Results', 15, 14);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const subtitle = `Ranked by Total Marks (Descending)${term ? '  |  ' + term : ''}${year ? '  ·  ' + year : ''}  |  Generated: ${new Date().toLocaleString()}`;
  doc.text(subtitle, 15, 22);

  const head = [['#', 'Student', 'Adm No', ...SUBJECTS.map(s => s.slice(0, 4)), 'Total', 'Avg%', 'Grd']];
  const body = rankings.map(r => [
    r.position,
    r.student_name,
    r.admission_number,
    ...SUBJECTS.map(s => r.subjects[s] ?? '—'),
    r.total_marks,
    `${r.average_percentage}%`,
    r.overall_grade,
  ]);

  autoTable(doc, {
    startY: 34,
    head,
    body,
    theme: 'striped',
    headStyles: { fillColor: [47, 102, 96], fontSize: 7 },
    bodyStyles: { fontSize: 7 },
    columnStyles: { 0: { cellWidth: 8, halign: 'center' } },
    margin: { left: 10, right: 10 },
  });

  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(160, 160, 160);
    doc.text(`Page ${i} of ${pages}  |  UDIRA HIGH SCHOOL`, 148, 205, null, null, 'center');
  }

  doc.save(`Rankings_${term || 'All'}_${year || 'All'}_${Date.now()}.pdf`);
};

